[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"

# Für C-Dateien
[[language]]
name = "c"
formatter = { command = "clang-format", args = ["--style=llvm"] }
indent = { tab-width = 2, unit = " "}
auto-format = true

# Für C++-Dateien
[[language]]
name = "cpp"
formatter = { command = "clang-format", args = ["--style=llvm"] }
indent = { tab-width = 2, unit = " "}
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "ron"
formatter = { command = "rondafk", args = ["--stdin"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]

[[language]]
name = "lua"
auto-format = true

[language-server.roc-ls]
command = "roc_language_server"

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
roots = []
comment-token = "#"
language-servers = ["roc-ls"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "roc", args = ["format", "--stdin", "--stdout"] }


[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[[grammar]]

name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "master" }
